### ISSUE TITLE
The name of this project?

### ISSUE THREAD

**Issue by lijunle** [qinezh/git-urls#1]
From github repo, it says `gitlink`, but from code example, it says `git-url`. However, npm show nothing for [`git-url`](https://www.npmjs.com/package/git-url).

What is the name for this project? It could better to be something no occupied.

**Comment by qinezh** [comment]
I have found `gitlink` has already been occupied in NPM. Now I change the project name to`git-urls`, as `git-url` has already been occupied too...

**Comment by lijunle** [comment]
I see.
