### ISSUE TITLE
URLs contain can contain repo secrets when basic auth is used to clone a repository

### ISSUE THREAD

**Issue by cjs** [qinezh/git-urls#24]
When a repository is cloned via 

```
git clone https://username:personal_access_token@github.com/username/repository.git
```

This, for better or worse logs the credential in `.git/config`. Here's a redacted example (`ghp_REDACTED` is the personal access token used in the `git clone`.

```
[remote "origin"]
        url = https://username:ghp_REDACTED@github.com/fakeuser/fakerepo
        fetch = +refs/heads/*:refs/remotes/origin/*
```

Unfortunately, the Git URL generated by "Copy Online Link" includes the user's credential and can be very easily accidentally leaked.

The real fix is to use a git credential store and never specify the credential when cloning. However, if `getUrlAsync` can strip off everything before and including the `@` it would help users avoid some embarrassing leaks.

**Comment by qinezh** [comment]
That makes sense to me, thank you for reporting the issue @cjs . Will take a look and fix it.

**Comment by qinezh** [comment]
The issue should be resolved in latest version: https://www.npmjs.com/package/git-urls, feel free to have a try 😃
